### PR TITLE
geodata pipeline #34

### PR DESCRIPTION
**Pull request by bucketteOfIvy**
Major changes in brief:
- Fixed [hopefully for all systems] runtime exceptions occurring during the FTP connection process for `download_all_files`
- Fixed exceptions in `add_name_to_dataframe` caused by renamed lookup files 
- Updated `get_geodata` to take a `--destination` parameter, which is passed to the export function (which were previously requesting but not receiving such a parameter). Default behavior is to export results to `.cache/geodata`. 
- Updated `add_herop_id_to_dataframe` function to align with modern `HEROP_ID` standard, or at least the standard seen in the jcoin package data*

Taken altogether this should resolve my portion of #34, with the `get_geodata` command now returning the correct file types. The only two things I cannot currently confirm function are the `zcta` geodata download -- as one of the needed files is ~500MB in size and takes forever to download -- and the pmtiles export -- as I do not have tippecanoe on my system. The latter isn't an issue for #34, but the former I'll try to resolve by just leaving this running overnight to see what the current output format is.

### CODE REVIEW

**Comment by bucketteOfIvy** [comment]
Oookay, tested this on the zcta data, and it does not complete in a time span of less than 6 hours.* Whatever is breaking seems to break during the file transfer process, so that I'm guessing something weird is happening on the Census' end of things (seeing as it only fails on one file from specifically the ZCTA data). 

*I can't confirm that it completes _after_ 6 six hours, just that it doesn't complete by the sixth hour.

**Comment by mradamcox** [comment]
Yeah, no worries, it definitely shouldn't take anywhere close to that long so something is up. I'll look into it when I get a chance to check out this PR.

**Comment by mradamcox** [comment]
Changing this back to a draft for now, as there are a few more things I want to fix up before merging, not least of which is adding some better documentation about this process.

**Review by mradamcox — APPROVED** [review]
Ok, ready to merge this now. I did a bit of an overhaul, and things are basically all set now. Added a little bit of documentation too, though more would be helpful. I've also written links to these files into a new [profile page](https://github.com/healthyregions) for our org, just for easier access if people want to download or reference them.

**Pull request merged**
